import React,{useState,useEffect} from 'react';
import type {PanelProps} from '@gsalgadotoledo/rt-app-admin-ui';
function CostChart({report}:{report:any}){
 const units=[...new Set<string>((report.daily??[]).map((p:any)=>p.unit))];const [unit,setUnit]=useState('USD');const selected=units.includes(unit)?unit:units[0];
 const points=(report.daily??[]).filter((p:any)=>p.unit===selected);const max=Math.max(...points.map((p:any)=>Math.abs(p.amount)),0.001);const width=900,height=260,step=width/Math.max(points.length,1);
 return <div style={{border:'1px solid #35414a',padding:20,margin:'20px 0'}}><h2>Daily charges · {selected??'No data'}</h2>{units.length>1&&<select value={selected} onChange={e=>setUnit(e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select>}
 {points.length?<svg viewBox={`0 0 ${width} ${height+45}`} role="img" aria-label="Daily AWS cost chart" style={{width:'100%',minHeight:240,maxHeight:420}}>{points.map((p:any,i:number)=>{const h=Math.abs(p.amount)/max*(height-28);return <g key={p.date}><rect x={i*step+3} y={height-h} width={Math.max(1,step-6)} height={h} fill={p.amount<0?'#d9ab73':'#82bca5'}><title>{p.date}: {p.amount.toFixed(4)} {p.unit}</title></rect>{(i%Math.max(1,Math.floor(points.length/10))===0||i===points.length-1)&&<text x={i*step+step/2} y={height+20} textAnchor="middle" fill="currentColor" fontSize="12">{p.date.slice(5)}</text>}</g>})}</svg>:<p>No daily billing data returned. Missing data is not zero cost.</p>}
 <p className="hint">Daily usage cost, through yesterday UTC. Credits are shown in amber. AWS billing data is delayed, generally updated at least daily; this is not real-time spend.</p></div>;
}
export default function AwsMonitorPanel({api}:PanelProps){
 const [budgets,setBudgets]=useState<any>();
 const [inventory,setInventory]=useState<any>(),[summary,setSummary]=useState<any>(),[detail,setDetail]=useState<any>();
 const [costSearch,setCostSearch]=useState(''),[costOrder,setCostOrder]=useState('descending');
 const [search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[auto,setAuto]=useState(false),[plan,setPlan]=useState<any>(),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState('');
 async function refresh(){setBusy(true);setError('');const reports=await Promise.allSettled([api('/aws/inventory'),api('/aws/costs'),api('/aws/budgets')]);if(reports[0].status==='fulfilled')setInventory(reports[0].value);if(reports[1].status==='fulfilled')setSummary(reports[1].value);if(reports[2].status==='fulfilled')setBudgets(reports[2].value);setError(reports.filter((r):r is PromiseRejectedResult=>r.status==='rejected').map(r=>r.reason.message).join(' · '));setBusy(false);}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(!auto)return;const timer=setInterval(()=>{if(!document.hidden)void refresh();},300000);return()=>clearInterval(timer);},[auto,api]);
 async function breakdown(service:string,kind:string){setBusy(true);try{setDetail(await api(`/aws/costs?service=${encodeURIComponent(service)}&detail=${kind}`));setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function prepare(arn:string,action:string){setBusy(true);setPlan(undefined);setConfirmation('');try{setPlan(await api('/aws/brake/plan','POST',{arn,action}));setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function execute(){setBusy(true);try{const result=await api('/aws/brake/execute','POST',{id:plan.id,confirmation});setMessage(result.message);setPlan(undefined);setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const costRows=(summary?.items??[]).filter((s:any)=>s.name.toLowerCase().includes(costSearch.toLowerCase())).slice().sort((a:any,b:any)=>a.unit.localeCompare(b.unit)||(costOrder==='descending'?b.amount-a.amount:a.amount-b.amount)||a.name.localeCompare(b.name));
 const totals=new Map<string,number>();for(const item of summary?.items??[])totals.set(item.unit,(totals.get(item.unit)??0)+item.amount);
 return <section><div className="section-head"><div><p className="eyebrow">AWS / OPERATIONS</p><h1>Resources, billing & emergency brake</h1></div><button disabled={busy} onClick={()=>void refresh()}>Refresh AWS</button></div>
 <p className="muted">Server credentials only: AWS_PROFILE, temporary environment credentials or an IAM role. Never enter AWS root keys here.</p>
 <label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Refresh every 5 minutes while this page is visible</label>
 <p className="hint">Inventory cache: 5 minutes. Cost cache: 6 hours per server process. Cost Explorer API queries are billable; refresh does not make AWS billing data more current.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {summary&&<><div className="stat-grid">{[...totals].map(([unit,total])=><div key={unit}><strong>{total.toFixed(2)} {unit}</strong><small>{summary.truncated?'Partial month-to-date charges':'Month-to-date reported charges'}</small></div>)}<div><strong>{summary.account??'—'}</strong><small>{summary.period.Start} → {summary.period.End} · end excluded</small></div></div><p className="hint">Fetched {new Date(summary.fetchedAt).toLocaleString()} · {summary.estimated?'Estimated':'Reported'} · UnblendedCost, including credits where returned.</p><CostChart report={summary}/>
 {summary.truncated&&<p role="alert">Partial AWS response. This is not the complete bill.</p>}
 <h2>Spend by service</h2><p className="hint">All services returned by Cost Explorer for this account, across regions; not limited to this application's resources. Amounts are grouped by currency.</p><div className="filters"><label>Service<input value={costSearch} onChange={e=>setCostSearch(e.target.value)} placeholder="Search services…"/></label><label>Sort by cost<select value={costOrder} onChange={e=>setCostOrder(e.target.value)}><option value="descending">Highest spend first</option><option value="ascending">Lowest spend first</option></select></label></div>
 <div className="table-wrap"><table><thead><tr><th>Service</th><th>Month-to-date charges</th><th>Breakdown · last 14 days</th></tr></thead><tbody>{costRows.map((s:any)=><tr key={s.name+s.unit}><td>{s.name}</td><td>{s.amount.toFixed(4)} {s.unit}</td><td><button disabled={busy} onClick={()=>void breakdown(s.name,'usage')}>Usage types</button> <button disabled={busy} onClick={()=>void breakdown(s.name,'resource')}>Resources</button></td></tr>)}</tbody></table></div></>}
 {detail&&<><h2>{detail.service} · {detail.detail==='usage'?'Usage charges':'Resource charges'}</h2><p className="hint">{detail.period.Start} → {detail.period.End}. Resource attribution must first be enabled in Cost Explorer. Unattributed cost does not identify a stoppable resource.</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Charges</th></tr></thead><tbody>{detail.items.map((s:any)=><tr key={s.name+s.unit}><td>{s.name}</td><td>{s.amount.toFixed(4)} {s.unit}</td></tr>)}</tbody></table></div>{detail.truncated&&<p>Partial detail report.</p>}</>}
 <h2>Spending guards</h2><p className="hint">Configure thresholds and recipients in infra/aws/spend-guards.auto.tfvars.json, then apply Terraform. AWS runs notifications and configured EC2/RDS stop actions even when this admin is closed. Billing is delayed: this is not a hard spending cap.</p>
 {budgets&&<><div className="table-wrap"><table><thead><tr><th>Budget</th><th>Services</th><th>Reported spend / limit</th></tr></thead><tbody>{budgets.items.map((b:any)=><tr key={b.name}><td>{b.name}</td><td>{b.services.join(', ')||'Account total'}</td><td>{b.spent??'Pending'} / {b.limit??'—'} {b.unit}</td></tr>)}</tbody></table></div>{!budgets.items.length&&<p>No AWS budgets configured.</p>}{budgets.truncated&&<p>Partial budget list.</p>}</>}
 <h2>Regional resources</h2><p className="hint">Tagged resources supported by the AWS Tagging API; not a complete account inventory or a live health report. Emergency actions verify current AWS state and Application tags before changing anything.</p>
 {inventory&&<><p>Account {inventory.account} · {inventory.region} · fetched {new Date(inventory.fetchedAt).toLocaleString()}</p>{inventory.truncated&&<p>Partial inventory: 300-resource limit.</p>}<input aria-label="Filter AWS resources" placeholder="Filter ARN, service, tags…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>Service</th><th>Resource</th><th>Emergency actions</th></tr></thead><tbody>{inventory.items.filter((r:any)=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map((r:any)=><tr key={r.arn}><td>{r.service}</td><td><code>{r.arn}</code><small>{Object.entries(r.tags).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small></td><td>{['lambda','ec2','rds'].includes(r.service)?<><button disabled={busy} onClick={()=>void prepare(r.arn,'pause')}>Plan pause</button> <button disabled={busy} onClick={()=>void prepare(r.arn,'resume')}>Plan resume</button></>:<span>No safe pause operation</span>}</td></tr>)}</tbody></table></div></>}
 {plan&&<div style={{border:'1px solid #bd8769',padding:20,marginTop:20}}><h2>Confirm {plan.action}</h2><code>{plan.arn}</code><p>{plan.warning}</p><p>No resources or data will be deleted. This is not a spending cap. Terraform or another operator may later change the configuration.</p><label>Type the exact ARN to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={busy||confirmation!==plan.arn} onClick={()=>void execute()}>Confirm {plan.action}</button> <button onClick={()=>setPlan(undefined)}>Cancel</button></div>}
 </section>;
}
