import test from 'node:test';
import assert from 'node:assert/strict';
import {createApplication,seedDemo} from '@gsalgadotoledo/rt-app-framework';
import {AdminIdentity,passwordVerifier} from '@gsalgadotoledo/rt-app-myadmin/backend';
import {MemoryStore} from '@gsalgadotoledo/rt-app-dynamodb';
import {LocalMailbox} from '@gsalgadotoledo/rt-app-auth';
const password='Root-Password-Test-2026!';
test('password-only admin has no database, isolates tokens and manages application users',async()=>{
 const store=new MemoryStore(),verifier=await passwordVerifier(password);
 const app=createApplication({store,mailer:new LocalMailbox(),secret:'signing-secret-'.repeat(4),adminPasswordVerifier:verifier});
 await app.migrate();await seedDemo(app,'Public-Password-2026!');
 let ip=0;
 const call=(method,path,body={},token)=>app.handle({method,path,body,query:{},headers:{authorization:token?'Bearer '+token:undefined},ip:String(ip++)});
 assert.equal((await call('POST','/admin/identity/auth/login',{password:'wrong'})).status,401);
 const root=await call('POST','/admin/identity/auth/login',{password});
 assert.equal(root.status,200);assert.equal(root.body.user.id,'rt-app-root');
 const token=root.body.token;
 assert.equal((await call('GET','/users/me',{},token)).status,401);
 const user=(await call('POST','/auth/login',{email:'owner@example.test',password:'Public-Password-2026!'})).body;
 assert.equal((await call('GET','/admin/modules',{},user.token)).status,401);
 assert.equal((await call('GET','/admin/app/users',{},token)).status,200);
 assert.equal((await call('GET','/admin/identity/users',{},token)).status,404);
 assert.equal((await call('POST','/admin/identity/auth/reset/request',{email:'root@example.test'})).status,404);
 assert.equal((await store.list('ADMIN#USERS')).items.length,0);
 const menus=await call('GET','/admin/modules',{},token);
 assert.ok(menus.body.every(m=>!m.id.startsWith('admin-')));
 const rotated=new AdminIdentity(await passwordVerifier('Rotated-Password-Test-2026!'),'signing-secret-'.repeat(4));
 await assert.rejects(rotated.auth.actor('Bearer '+token),e=>e.status===401);
});
test('admin fails closed without configuration and throttles invalid password attempts',async()=>{
 await assert.rejects(passwordVerifier('short'));
 const disabled=new AdminIdentity(undefined,'disabled-secret-'.repeat(4));
 await assert.rejects(disabled.login(password,'ip'),e=>e.status===503);
 const admin=new AdminIdentity(await passwordVerifier(password),'another-secret-'.repeat(4));
 for(let i=0;i<5;i++)await assert.rejects(admin.login('wrong','ip'),e=>e.status===401);
 await assert.rejects(admin.login(password,'ip'),e=>e.status===429);
 assert.ok((await admin.login(password,'other-ip')).token);
});
test('explicit local admin access needs no password and does not authenticate public users', async()=>{
 const app=createApplication({store:new MemoryStore(),mailer:new LocalMailbox(),secret:'local-test-secret-'.repeat(4),localAdminAccess:true});
 await app.migrate();
 const call=path=>app.handle({method:'GET',path,body:{},query:{},headers:{},ip:'127.0.0.1'});
 assert.equal((await call('/admin/modules')).status,200);
 assert.equal((await call('/admin/app/users')).status,200);
 assert.equal((await call('/users/me')).status,401);
 const secured=createApplication({store:new MemoryStore(),mailer:new LocalMailbox(),secret:'remote-test-secret-'.repeat(4)});
 assert.equal((await secured.handle({method:'GET',path:'/admin/modules',body:{},query:{},headers:{},ip:'127.0.0.1'})).status,401);
});
test('root sessions refresh through the application store and die with logout or a new password',async()=>{
 const store=new MemoryStore(),verifier=await passwordVerifier(password),secret='root-session-secret-'.repeat(3);
 const app=createApplication({store,mailer:new LocalMailbox(),secret,adminPasswordVerifier:verifier});
 await app.migrate();
 let ip=0;
 const call=(method,path,body={},token)=>app.handle({method,path,body,query:{},headers:{authorization:token?'Bearer '+token:undefined},ip:'10.0.0.'+(ip++)});
 const root=(await call('POST','/admin/identity/auth/login',{password})).body;
 assert.equal(root.expiresIn,900);assert.match(root.refreshToken,/^[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}$/);assert.equal(root.refreshToken.split('.')[0],root.sessionId);
 assert.equal((await store.get('SESSIONS#rt-app-root',root.sessionId)).data.provider.startsWith('admin:'),true);
 const next=await call('POST','/admin/identity/auth/refresh',{refreshToken:root.refreshToken});
 assert.equal(next.status,200);assert.equal(next.body.sessionId,root.sessionId);
 assert.equal((await call('GET','/admin/modules',{},next.body.token)).status,200);
 // Root refresh tokens are not application refresh tokens and vice versa.
 assert.equal((await call('POST','/auth/refresh',{refreshToken:next.body.refreshToken})).status,401);
 assert.equal((await call('POST','/admin/identity/auth/refresh',{refreshToken:'garbage'})).body.error,'Invalid session');
 // A new ADMIN_PASSWORD ends every root session, even with the same store.
 const rotated=new AdminIdentity(await passwordVerifier('Rotated-Password-Test-2026!'),secret,false,store);
 await assert.rejects(rotated.refresh(next.body.refreshToken,'x'),e=>e.status===401);
 assert.equal((await call('POST','/admin/identity/auth/logout',{},next.body.token)).status,200);
 assert.equal((await call('GET','/admin/modules',{},next.body.token)).status,401);
 assert.equal((await call('POST','/admin/identity/auth/refresh',{refreshToken:next.body.refreshToken})).status,401);
 const stateless=new AdminIdentity(verifier,secret);
 const plain=await stateless.login(password,'y');assert.equal(plain.refreshToken,undefined);
 await assert.rejects(stateless.refresh(root.refreshToken,'y'),e=>e.status===401);
});
