variable "stripe_api_key" {
  description = "Stripe secret key (sk_test_… while trying, sk_live_… for production). Leave empty to use STRIPE_API_KEY. Find it at https://dashboard.stripe.com/apikeys"
  type        = string
  sensitive   = true
  default     = null
}

variable "namespace" {
  description = "Prefix for price lookup keys and metadata, so several apps can share one Stripe account. Lowercase letters, digits and hyphens."
  type        = string
  default     = "rt-app"
  validation {
    condition     = can(regex("^[a-z0-9-]{2,40}$", var.namespace))
    error_message = "Use 2-40 lowercase letters, digits or hyphens."
  }
}

variable "plans" {
  description = "Subscription plans of the subscriptions module. Generated by `npm run stripe:plans` into plans.auto.tfvars.json; free and disabled plans are skipped. See https://docs.stripe.com/products-prices/overview"
  type = list(object({
    id          = string
    name        = string
    amount      = number
    currency    = string
    periodDays  = number
    description = optional(string, "")
    enabled     = optional(bool, true)
  }))
  default = []
  validation {
    condition     = alltrue([for p in var.plans : p.amount >= 0 && floor(p.amount) == p.amount && p.periodDays >= 1 && p.periodDays <= 366])
    error_message = "amount must be a whole number of minor units (cents) and periodDays between 1 and 366."
  }
}
