import "@gsalgadotoledo/rt-app-admin-ui/themes.css";
import React,{useEffect,useState,useRef} from 'react';
import './style.css';
import './workspace.css';
import {themes} from './themes.js';
import {ThemeFx} from './ThemeFx.js';
import {ProjectPower,MemoryGauge} from './ProjectPower.js';
import {ActionMenu,type MenuAction} from './ActionMenu.js';
import {DependencyInstall,needsInstall,type InstallClient} from './DependencyInstall.js';
import {DeployPanel,type DeployClient} from './DeployPanel.js';
import {CreateProjectWizard} from './CreateProjectWizard.js';
import {ServiceControls,type ServiceAdmin} from './ServiceControls.js';
import {MachineProcesses,type MachineClient} from './MachineProcesses.js';
import {TerraformPanel,type TerraformClient} from './TerraformPanel.js';
import {ContractsPanel,type ContractsClient} from './ContractsPanel.js';
export interface Service {runtime?:string|null;id:string;label:string;kind:string;enabled:boolean;state:string;pid:number|null;url:string|null;error:string|null;exitCode:number|null;cpu:number;cpuTimeMs?:number;threads?:number|null;memoryMb:number;uptimeSeconds:number|null;dependencies:string[];scope?:'global'|'project';project?:string;ports?:number[];background?:boolean;admin?:ServiceAdmin}
export interface Output {sequence:number;time:number;stream:string;text:string}
export interface Tool {id:string;name:string;description:string;kind:string;installed:boolean;job?:{state:string;message:string}}
export interface Candidate {id:string;label:string;cwd:string;command:string[];source:string}
export interface Snapshot {project:string;services:Service[];projects?:{name:string;path:string;kind?:string;runtimes?:string[];running?:number}[];projectKind?:string;projectRuntimes?:string[];globalPorts?:Record<string,number>;projectPorts?:Record<string,number>;catalog?:Tool[]}
export interface ProjectSetup {backends:{id:string;name:string;description:string}[];templates:{id:string;name:string;description:string;prompt?:string}[];initializer?:string;requirements:{id:string;name:string;required:boolean;ready:boolean;installedVersion:string;description:string}[];workspace:string;job:{state:string;log:string[];error?:string;result?:{path?:string}}}
export interface CommandGroup {id:string;label:string;cwd:string;commands:{id:string;name:string;description:string;command:string[];serviceId?:string}[]}
export interface ManagerClient extends DeployClient, MachineClient, TerraformClient, ContractsClient, InstallClient {background?(id:string,enabled:boolean):Promise<Snapshot>;openAdmin?(id:string):Promise<void>;deleteProject?(path:string):Promise<Snapshot>;commands?():Promise<CommandGroup[]>;runCommand?(id:string):Promise<{id:string}>;dropFolder?(file:File):Promise<{kind:string;snapshot?:Snapshot}>;openProjectLocation?(target:'folder'|'vscode'|'cursor'|'editor',path:string):Promise<void>;copyText?(text:string):Promise<void>;projectStatus?(id:string,backendId?:string):Promise<ProjectSetup>;chooseWorkspace?():Promise<string>;installTools?(ids:string[]):Promise<unknown>;createProject?(spec:{name:string;templateId:string;backendId:string}):Promise<unknown>;snapshot():Promise<Snapshot>;action(action:'start'|'stop'|'restart',id:string):Promise<unknown>;logs(id:string):Promise<Output[]>;openUrl?(id:string):Promise<void>;selectProject?(path?:string):Promise<Snapshot>;catalogAction?(action:'add'|'remove',id:string):Promise<unknown>;discover?():Promise<Candidate[]>;addDiscovered?(id:string):Promise<Snapshot>;setPorts?(scope:'global'|'project',ports:Record<string,number>):Promise<Snapshot>}
function ProjectIcon({kind}:{kind:'folder'|'vscode'|'cursor'}) {
 const paths={folder:'M3 7h6l2 2h10v11H3z M3 7V4h6l2 3h10v2',vscode:'M16 3l5 2v14l-5 2-9-8-3 3-2-2 4-4-4-4 2-2 3 3 9-8v18 M7 10l9 7V7l-9 6',cursor:'M5 3l14 9-6 1-3 7-5-17z'};
 return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]}/></svg>;
}
function ActionIcon({action}:{action:'start'|'stop'|'restart'}) {
 return <svg className="rt-action-icon" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false">
  {action==='start'?<path d="M7 4l14 8-14 8z" fill="currentColor" stroke="none"/>:action==='stop'?<rect x="5" y="5" width="14" height="14" rx="1" fill="currentColor" stroke="none"/>:<><path d="M20 7v5h-5"/><path d="M20 12a8 8 0 1 0-2 5M20 7v5"/></>}
 </svg>;
}
function SidebarIcon({kind}:{kind:'contracts'|'themes'|'processes'|'shared'}) {
 const paths={contracts:'M7 3h7l5 5v13H7z M14 3v5h5 M10 13h6 M10 17h6',themes:'M12 3a9 9 0 1 0 0 18c1.2 0 2-.8 2-1.8 0-1.3-1-1.6-1-2.7 0-1 .8-1.5 1.8-1.5H17a4 4 0 0 0 4-4c0-4.4-4-8-9-8z M7.5 11.5h.01 M10 7.5h.01 M14.5 7.5h.01',processes:'M4 5h16v11H4z M8 20h8 M12 16v4 M7 12l2-3 2 2 3-4 3 5',shared:'M12 3l8 4-8 4-8-4z M4 12l8 4 8-4 M4 17l8 4 8-4'};
 return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]}/></svg>;
}
function RunningBadge({count}:{count:number}) {
 return count>0?<span className="rt-running-badge" title={`${count} running`}><i aria-hidden="true"/>{count}</span>:null;
}
const SIDEBAR_WIDTH={min:200,max:480,initial:280};
/** Services with a browser page, in the order they are offered as "Open …" buttons. */
const OPEN_TARGETS:[string,string][]=[['ssr','SSR site'],['spa','SPA app'],['admin','Admin'],['api','API'],['mail','Mail']];
export function ServiceManager({client}:{client:ManagerClient}) {
 const [theme,setTheme]=useState(()=>{try{const saved=localStorage.getItem('rt-app.services.theme');return themes.some(t=>t[0]===saved)?saved!:'violet';}catch{return 'violet';}});
 useEffect(()=>{try{localStorage.setItem('rt-app.services.theme',theme);}catch{}},[theme]);
 const [themesOpen,setThemesOpen]=useState(false);
 const [missingDeps,setMissingDeps]=useState<{path:string;error:string}>();
 const [sidebarWidth,setSidebarWidth]=useState(()=>{try{const saved=Number(localStorage.getItem('rt-app.services.sidebar'));return saved>=SIDEBAR_WIDTH.min&&saved<=SIDEBAR_WIDTH.max?saved:SIDEBAR_WIDTH.initial;}catch{return SIDEBAR_WIDTH.initial;}});
 useEffect(()=>{try{localStorage.setItem('rt-app.services.sidebar',String(sidebarWidth));}catch{}},[sidebarWidth]);
 function resizeSidebar(event:React.PointerEvent){event.preventDefault();const start=event.clientX,width=sidebarWidth;const move=(e:PointerEvent)=>setSidebarWidth(Math.min(SIDEBAR_WIDTH.max,Math.max(SIDEBAR_WIDTH.min,width+e.clientX-start)));const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);document.body.classList.remove('rt-resizing');};document.body.classList.add('rt-resizing');window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);}
 const [commandsOpen,setCommandsOpen]=useState(false);
 const [commandGroups,setCommandGroups]=useState<CommandGroup[]>([]);
 const [commandSelections,setCommandSelections]=useState<Record<string,string>>({});
 const [dragging,setDragging]=useState(false);
 const [creating,setCreating]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);
 const [snapshot,setSnapshot]=useState<Snapshot>({project:'',services:[]});
 const [catalogOpen,setCatalogOpen]=useState(false);const [candidates,setCandidates]=useState<Candidate[]>([]);const [scanned,setScanned]=useState(false);
 const [scope,setScope]=useState<'global'|'project'>('project');const [editing,setEditing]=useState(false);const [ports,setPorts]=useState<Record<string,number>>({});
 const [detail,setDetail]=useState(false);
 const [deployOpen,setDeployOpen]=useState(false);
 const [machineOpen,setMachineOpen]=useState(false);const [terraformOpen,setTerraformOpen]=useState(false);const [contractsOpen,setContractsOpen]=useState(false);
 const [selected,setSelected]=useState('api');const [logs,setLogs]=useState<Output[]>([]);const [error,setError]=useState('');const [connectionError,setConnectionError]=useState('');const [busy,setBusy]=useState(false);const [follow,setFollow]=useState(true);const [copied,setCopied]=useState(false);const following=useRef(true);const output=useRef<HTMLPreElement>(null);
 useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const next=await client.snapshot();if(cancelled)return;setSnapshot(next);const id=next.services.some(s=>s.id===selected&&(s.scope??'project')===scope)?selected:next.services.find(s=>(s.scope??'project')===scope)?.id;if(id!==selected){setSelected(id??'');return;}if(id&&detail){const rows=await client.logs(id);if(!cancelled)setLogs(rows);}setConnectionError('');}catch(e){if(!cancelled)setConnectionError((e as Error).message);}finally{if(!cancelled)timer=setTimeout(poll,1000);}}void poll();return()=>{cancelled=true;clearTimeout(timer);};},[client,selected,scope,detail]);
 function changeFollow(value:boolean){following.current=value;setFollow(value);}
 useEffect(()=>{if(following.current&&output.current)output.current.scrollTop=output.current.scrollHeight;},[logs,follow]);
 useEffect(()=>{setCopied(false);},[selected,snapshot.project]);
 useEffect(()=>{if(!copied)return;const timer=setTimeout(()=>setCopied(false),2000);return()=>clearTimeout(timer);},[copied]);
 async function copyOutput(){const text=logs.map(row=>`${new Date(Number(row.time)).toLocaleTimeString()} [${row.stream}] ${row.text}`).join('\n');try{if(client.copyText)await client.copyText(text);else await navigator.clipboard.writeText(text);setCopied(true);}catch(e){setError('Could not copy output: '+(e as Error).message);}}

 async function action(command:'start'|'stop'|'restart',id:string){setBusy(true);try{await client.action(command,id);setSnapshot(await client.snapshot());setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function selectProject(path?:string){setBusy(true);setConfirmDelete(false);try{const next=await client.selectProject?.(path);setMissingDeps(undefined);if(next){setThemesOpen(false);setSnapshot(next);setCommandsOpen(false);setCommandGroups([]);setSelected('api');setLogs([]);setScope('project');setCommandsOpen(false);setDetail(false);setEditing(false);setScanned(false);setCandidates([]);setError('');}}catch(e){const message=(e as Error).message;if(path&&needsInstall(message)){setMissingDeps({path,error:message});setError('');}else setError(message);}finally{setBusy(false);}}
 async function deleteProject(){setBusy(true);try{const next=await client.deleteProject!(snapshot.project);setConfirmDelete(false);setSnapshot(next);setLogs([]);setDetail(false);setCommandsOpen(false);setDeployOpen(false);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openLocation(target:'folder'|'vscode'|'cursor'|'editor'){try{await client.openProjectLocation?.(target,snapshot.project);setError('');}catch(e){setError((e as Error).message);}}
 async function savePorts(){setBusy(true);try{const next=await client.setPorts?.(scope,ports);if(next)setSnapshot(next);setEditing(false);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function toolAction(action:'add'|'remove',id:string){try{await client.catalogAction?.(action,id);setSnapshot(await client.snapshot());setError('');}catch(e){setError((e as Error).message);}}
 async function showCommands(){setBusy(true);try{setCommandGroups(await client.commands?.()??[]);setCommandsOpen(true);setDetail(false);setThemesOpen(false);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function runSelected(id:string){setBusy(true);try{const run=await client.runCommand?.(id);if(run){setSnapshot(await client.snapshot());setSelected(run.id);setLogs([]);setScope('project');setCommandsOpen(false);setDetail(true);changeFollow(true);}setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function scan(){try{setCandidates(await client.discover?.()??[]);setScanned(true);}catch(e){setError((e as Error).message);}}
 async function addCandidate(id:string){setBusy(true);try{const next=await client.addDiscovered?.(id);if(next)setSnapshot(next);setCandidates(candidates.filter(c=>c.id!==id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=snapshot.services.filter(s=>(s.scope??'project')===scope).sort((a,b)=>Number(b.kind==='task')-Number(a.kind==='task'));const current=snapshot.services.find(s=>s.id===selected);
 const projectRunning=snapshot.services.some(s=>(s.scope??'project')==='project'&&s.state==='running');const sharedRunning=snapshot.services.filter(s=>s.scope==='global'&&s.pid&&['running','starting','waiting'].includes(s.state)).length;
 function openService(id:string){setSelected(id);setLogs([]);setDetail(true);changeFollow(true);}
 const icon=(d:string)=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={d}/></svg>;
 const projectActions:MenuAction[]=[
  ...(client.setPorts?[{label:'Configure ports',hint:'Configure local ports and restart affected active services',icon:icon('M4 7h16 M4 17h16 M8 4v6 M16 14v6'),disabled:busy,onSelect:()=>{setDetail(false);setPorts({... (scope==='global'?snapshot.globalPorts:snapshot.projectPorts)});setEditing(true);}}]:[]),
  ...(scope==='global'?[{label:'Add tools & services',icon:icon('M12 5v14 M5 12h14'),onSelect:()=>setCatalogOpen(true)}]:[]),
  ...(scope==='project'&&client.commands?[{label:'Commands',hint:'List scripts and run a command separately',icon:icon('M5 7l5 5-5 5 M12 17h7'),disabled:busy,onSelect:()=>void showCommands()}]:[]),
  ...(scope==='project'&&client.deployInfo?[{label:'Deploy',hint:'Providers, targets per environment and GitHub',icon:icon('M12 3l7 7h-4v8H9v-8H5z'),disabled:busy||!snapshot.project,onSelect:()=>{setDetail(false);setCommandsOpen(false);setDeployOpen(true);}}]:[]),
  ...(scope==='project'?[{label:'Discover services',hint:'Find runnable services in the selected project',icon:icon('M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14z M21 21l-5-5'),disabled:busy,onSelect:()=>{setDetail(false);void scan();}}]:[]),
  ...(scope==='project'&&client.openProjectLocation?[{label:'Open project folder',separator:true,icon:icon('M3 7h6l2 2h10v11H3z'),disabled:!snapshot.project,onSelect:()=>void openLocation('folder')},{label:'Open in editor',hint:'Cursor → VS Code → project folder',icon:icon('M8 9l-4 3 4 3 M16 9l4 3-4 3 M13 6l-2 12'),disabled:!snapshot.project,onSelect:()=>void openLocation('editor')}]:[]),
  ...(scope==='project'&&client.selectProject?[{label:'Open another project…',icon:icon('M4 4h16v16H4z M4 9h16'),disabled:busy,onSelect:()=>void selectProject()}]:[]),
  ...(scope==='project'&&client.deleteProject&&snapshot.project?[{label:'Delete project…',separator:true,danger:true,hint:'Stop this project and move its folder to the Trash',icon:icon('M4 7h16 M9 7V4h6v3 M6 7l1 13h10l1-13'),disabled:busy,onSelect:()=>setConfirmDelete(true)}]:[]),
 ];
 async function dropFolder(event:React.DragEvent){event.preventDefault();setDragging(false);if(busy||creating)return;const files=Array.from(event.dataTransfer.files);if(files.length!==1){setError('Drop one folder at a time.');return;}if(!client.dropFolder){setError('Folder dropping is available in the desktop application.');return;}setBusy(true);try{const result=await client.dropFolder(files[0]);setDetail(false);setLogs([]);setError('');setScope('project');setEditing(false);setScanned(false);setCandidates([]);if(result.snapshot){setThemesOpen(false);setSnapshot(result.snapshot);setSelected('api');setCreating(false);}else{setThemesOpen(false);setCreating(true);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="rt-services" data-rt-theme={theme} onDragOver={e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();setDragging(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false);}} onDrop={e=>void dropFolder(e)}>
 {dragging&&<div className="rt-folder-drop-overlay">Drop a folder to open a project or create one in this workspace</div>}

  <div className="rt-dashboard-layout" style={{['--rt-sidebar-width' as string]:`${sidebarWidth}px`}}><ThemeFx theme={theme} running={projectRunning}/><aside className="rt-dashboard-sidebar">
   <div className="rt-sidebar-head"><span className="rt-services-kicker">PROJECTS</span>{client.createProject&&<button className="rt-new-project" disabled={busy} onClick={()=>{setThemesOpen(false);setCreating(true);}}><span aria-hidden="true">＋</span> New project</button>}</div>
   <nav className="rt-project-list" aria-label="Projects">{snapshot.projects?.map(p=><button key={p.path} title={p.path} disabled={busy} aria-current={!creating&&!themesOpen&&!machineOpen&&!terraformOpen&&!contractsOpen&&scope==='project'&&p.path===snapshot.project?'page':undefined} onClick={()=>{setCreating(false);setThemesOpen(false);setMachineOpen(false);setTerraformOpen(false);setContractsOpen(false);setScope('project');setCommandsOpen(false);setDeployOpen(false);setDetail(false);setEditing(false);if(p.path!==snapshot.project)void selectProject(p.path);}}><strong><span>{p.name}</span><RunningBadge count={p.running??0}/></strong><small>{(p.runtimes??[]).map(r=>({node:'Node',python:'Python',go:'Go',rust:'Rust',cpp:'C/C++'} as Record<string,string>)[r]??r).join(' · ')||p.path.split('/').slice(-2,-1)[0]}{p.kind==='rt-app'?' · RT-App':''}</small></button>)}{!snapshot.projects?.length&&<p className="rt-sidebar-empty">No projects yet. Create one or drop a folder here.</p>}</nav>
   <div className="rt-sidebar-footer"><button disabled={busy} aria-pressed={!creating&&!themesOpen&&!machineOpen&&!terraformOpen&&!contractsOpen&&scope==='global'} onClick={()=>{setCreating(false);setThemesOpen(false);setMachineOpen(false);setTerraformOpen(false);setContractsOpen(false);setScope('global');setCommandsOpen(false);setDeployOpen(false);setDetail(false);setEditing(false);}}><SidebarIcon kind="shared"/><span>Shared services</span><RunningBadge count={sharedRunning}/></button>{client.machineProcesses&&<button aria-pressed={machineOpen} onClick={()=>{setCreating(false);setThemesOpen(false);setTerraformOpen(false);setContractsOpen(false);setMachineOpen(true);}}><SidebarIcon kind="processes"/><span>Running processes</span></button>}
    <div className="rt-sidebar-icons">{client.contracts&&<button className="rt-sidebar-icon" aria-label="Contracts" title="Contracts" aria-pressed={contractsOpen} onClick={()=>{setCreating(false);setThemesOpen(false);setMachineOpen(false);setTerraformOpen(false);setContractsOpen(true);}}><SidebarIcon kind="contracts"/></button>}<button className="rt-sidebar-icon" aria-label="Themes" title="Themes" aria-pressed={themesOpen} onClick={()=>{setCreating(false);setMachineOpen(false);setTerraformOpen(false);setContractsOpen(false);setThemesOpen(true);}}><SidebarIcon kind="themes"/></button></div></div>
   <div className="rt-sidebar-resize" role="separator" aria-orientation="vertical" aria-label="Resize sidebar" aria-valuemin={SIDEBAR_WIDTH.min} aria-valuemax={SIDEBAR_WIDTH.max} aria-valuenow={sidebarWidth} tabIndex={0} onPointerDown={resizeSidebar} onDoubleClick={()=>setSidebarWidth(SIDEBAR_WIDTH.initial)} onKeyDown={e=>{if(e.key==='ArrowLeft')setSidebarWidth(w=>Math.max(SIDEBAR_WIDTH.min,w-16));if(e.key==='ArrowRight')setSidebarWidth(w=>Math.min(SIDEBAR_WIDTH.max,w+16));}}/>
  </aside><main className="rt-dashboard-main">
  {themesOpen ? <section className="rt-theme-gallery" aria-label="Appearance themes">
   <header><div className="rt-services-kicker">APPEARANCE</div><h2>Themes</h2><p>Pick a look. Changes apply immediately and are saved on this computer.</p></header>
   <div className="rt-theme-grid rt-theme-grid-compact">{themes.map(([id,title,description])=><button type="button" className="rt-theme-card" key={id} aria-label={`Apply ${title} theme`} aria-pressed={theme===id} onClick={()=>setTheme(id)}>
    <span className="rt-theme-preview" data-rt-theme={id} aria-hidden="true"><span className="rt-theme-preview-sidebar"><i/><i/><i/></span><span className="rt-theme-preview-content"><span className="rt-theme-preview-title">API <b>●</b></span><span className="rt-theme-preview-toolbar"><i/><i/></span><span className="rt-theme-swatches"><i/><i/><i/><i/></span></span></span>
    <span className="rt-theme-card-heading"><strong>{title}</strong>{theme===id&&<span>✓</span>}</span><span className="rt-theme-description">{description}</span>
   </button>)}</div><p className="rt-theme-current" role="status">Current theme: {themes.find(t=>t[0]===theme)?.[1]}</p>
  </section> : <>

  {machineOpen&&!creating&&<MachineProcesses client={client}/>}
  {contractsOpen&&!creating&&<ContractsPanel client={client}/>}
  {creating&&<CreateProjectWizard client={client} onClose={()=>setCreating(false)} onOpen={path=>{setCreating(false);void selectProject(path);}}/>}
  {!snapshot.project&&!creating&&!machineOpen&&!terraformOpen&&!contractsOpen&&scope==='project'&&<div className="rt-project-empty rt-folder-drop-empty"><h2>A workspace for your applications</h2><p>Drop a folder here to open an RT-App project or use it as a workspace for a new project.</p><button onClick={()=>{setThemesOpen(false);setCreating(true);}}>Create your first project</button></div>}
  {(error||connectionError)&&<p role="alert" className="rt-services-error">{error||connectionError}</p>}
  {missingDeps&&!creating&&<DependencyInstall key={missingDeps.path} client={client} path={missingDeps.path} name={snapshot.projects?.find(p=>p.path===missingDeps.path)?.name??missingDeps.path.split('/').pop()!} error={missingDeps.error} onInstalled={()=>void selectProject(missingDeps.path)} onDismiss={()=>setMissingDeps(undefined)}/>}
  {!creating&&!machineOpen&&!terraformOpen&&!contractsOpen&&(snapshot.project||scope==='global')&&<>
  <section className="rt-project-overview rt-project-header" aria-label={scope==='project'?'Selected project controls':'Global service controls'}><div><div className="rt-services-kicker">{scope==='project'?'SELECTED PROJECT':'SHARED INFRASTRUCTURE'}</div><div className="rt-project-title"><h2>{scope==='project'?(snapshot.projects?.find(p=>p.path===snapshot.project)?.name||'No project selected'):'Global services'}</h2><ActionMenu label={scope==='project'?'Project actions':'Shared services actions'} actions={projectActions}/></div><p title={snapshot.project}>{scope==='project'?snapshot.project:'Shared across projects · stopping these services affects their consumers'}</p></div><ProjectPower services={snapshot.services.filter(s=>(s.scope??'project')===scope)} busy={busy||(scope==='project'&&!snapshot.project)} label={scope==='project'?(snapshot.projects?.find(p=>p.path===snapshot.project)?.name??'project'):'shared services'} onToggleAll={command=>void action(command,scope==='project'?'project:all':'global:all')} onRestartAll={()=>void action('restart',scope==='project'?'project:all':'global:all')} onAction={(command,id)=>void action(command,id)} onOpen={openService} onOpenUrl={client.openUrl?id=>void client.openUrl!(id).catch(e=>setError(e.message)):undefined} onBackground={client.background?(id,enabled)=>void (async()=>{setBusy(true);try{setSnapshot(await client.background!(id,enabled));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}})():undefined} onAdmin={client.openAdmin?id=>void client.openAdmin!(id).catch(e=>setError(e.message)):undefined}/></section>
  {scope==='project'&&snapshot.project&&client.openUrl&&<nav className="rt-open-bar" aria-label="Open the application">{OPEN_TARGETS.map(([id,label])=>{const service=snapshot.services.find(s=>s.id===id&&(s.scope??'project')==='project');if(!service?.url)return null;const live=service.state==='running';return <button key={id} className={live?'rt-open live':'rt-open'} title={live?service.url:`${service.label} is ${service.state}; start the project first`} disabled={!live} onClick={()=>void client.openUrl!(id).catch(e=>setError(e.message))}><span>Open {label}</span><small>{live?service.url.replace(/^https?:\/\//,''):service.state}</small></button>;})}</nav>}
  {confirmDelete&&scope==='project'&&snapshot.project&&<section className="rt-delete-confirm" role="alertdialog" aria-label="Delete project">
   <p><strong>Delete {snapshot.projects?.find(p=>p.path===snapshot.project)?.name??'this project'}?</strong> Its services stop and the folder <code>{snapshot.project}</code> moves to the Trash. You can restore it from the Trash; the GitHub repository is not touched.</p>
   <div className="rt-services-toolbar"><button className="rt-danger" disabled={busy} onClick={()=>void deleteProject()}>Yes, delete project</button><button disabled={busy} onClick={()=>setConfirmDelete(false)}>Cancel</button></div>
  </section>}
  {!detail&&deployOpen&&scope==='project'&&<DeployPanel client={client} onClose={()=>setDeployOpen(false)}/>}
  {!detail&&!deployOpen&&commandsOpen&&scope==='project'&&<section aria-label="Project commands" className="rt-command-catalog">
   <div className="rt-services-toolbar"><h3>Application commands</h3><button disabled={busy} onClick={()=>void showCommands()}>Refresh</button><button onClick={()=>setCommandsOpen(false)}>Close</button></div>
   <p>Dev uses the managed service. Other commands run in a separate process with their own output. Tests and builds may finish; watch commands keep running.</p>
   {commandGroups.map(group=>{const choice=group.commands.find(c=>c.id===commandSelections[group.id])??group.commands.find(c=>c.name==='dev')??group.commands[0];return <article key={group.id} className="rt-command-row"><div><strong>{group.label}</strong><small>{group.cwd}</small></div><label>Command<select aria-label={`Command for ${group.label}`} value={choice.id} onChange={e=>setCommandSelections({...commandSelections,[group.id]:e.target.value})}>{group.commands.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><code title={choice.description}>{choice.description||choice.command.join(' ')}</code><button disabled={busy} title={`Run ${choice.name} for ${group.label}`} onClick={()=>void runSelected(choice.id)}><ActionIcon action="start"/>Run</button></article>;})}
   {!commandGroups.length&&<p>No commands found. Add package.json scripts or rt-app.commands.json.</p>}
  </section>}
  {!detail&&!commandsOpen&&!deployOpen&&<>
    {scope==='global'&&catalogOpen&&<div className="rt-services-catalog"><div className="rt-services-catalog-head"><strong>Add tools & services</strong><button onClick={()=>setCatalogOpen(false)}>Close</button></div>{snapshot.catalog?.map(tool=><article key={tool.id}><strong>{tool.name}</strong><span>{tool.kind==='embedded'?'Embedded tool · no server':tool.kind==='cli'?'Command-line tool · added to PATH':'Managed local service'}</span><p>{tool.description}</p><small>{tool.job?.message}</small><button disabled={tool.job?.state==='installing'} onClick={()=>void toolAction(tool.installed?'remove':'add',tool.id)}>{tool.job?.state==='installing'?'Installing…':tool.installed?'Remove · keep data':'Add & install'}</button></article>)}</div>}
  {scope==='project'&&scanned&&<div className="rt-services-catalog"><div className="rt-services-catalog-head"><strong>Discovered services</strong><button onClick={()=>{setScanned(false);setCandidates([]);}}>Close</button></div>{candidates.length?candidates.map(candidate=><article key={candidate.id}><strong>{candidate.label}</strong><span>{candidate.cwd} · {candidate.source}</span><code>{candidate.command.join(' ')}</code><button disabled={busy} onClick={()=>void addCandidate(candidate.id)}>Add service</button></article>):<p>No additional runnable projects found. Custom commands can be added in rt-app.settings.json.</p>}</div>}


  {editing&&<form className="rt-services-port-form" onSubmit={e=>{e.preventDefault();void savePorts();}}>{Object.entries(ports).map(([name,port])=><label key={name}>{name}<input aria-label={`${name} port`} type="number" min="1024" max="65535" required value={port} onChange={e=>setPorts({...ports,[name]:Number(e.target.value)})}/></label>)}<button disabled={busy}>Save & restart active services</button><button type="button" onClick={()=>setEditing(false)}>Cancel</button></form>}
  {(scope==='global'||!client.terraform)&&<div className="rt-services-table"><table><thead><tr><th>Service</th><th>PID</th><th>CPU</th><th>Memory</th><th>URL</th><th>Status</th><th>Controls</th></tr></thead><tbody>{visible.map(service=><tr key={service.id} className={selected===service.id?'selected':''} onClick={()=>{setSelected(service.id);setLogs([]);setDetail(true);changeFollow(true);}}><td><button className="rt-services-name" onClick={e=>{e.stopPropagation();setSelected(service.id);setLogs([]);setDetail(true);changeFollow(true);}}>{service.label}</button>{service.runtime&&<span className="rt-runtime-badge" title="Configured runtime">{service.runtime}</span>}<small>{service.project??'Local service'}{service.pid?` · PID ${service.pid}`:''}</small></td><td>{service.pid??'—'}</td><td>{service.pid?`${service.cpu.toFixed(1)}%`:'—'}</td><td><MemoryGauge mb={service.memoryMb} cpu={service.cpu} active={Boolean(service.pid)} size={30}/></td><td>{service.url?<button className="rt-services-link" onClick={e=>{e.stopPropagation();void client.openUrl?.(service.id).catch(e=>setError(e.message));}}>{service.url.replace('http://','')} ↗</button>:'—'}</td><td><span className={`rt-services-status state-${service.state}`}><i/>{service.state}</span></td><td><ServiceControls service={service} busy={busy} onAction={command=>void action(command,service.id)} onLogs={()=>{setSelected(service.id);setLogs([]);setDetail(true);changeFollow(true);}} onBackground={client.background?enabled=>void (async()=>{setBusy(true);try{setSnapshot(await client.background!(service.id,enabled));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}})():undefined} onAdmin={client.openAdmin?()=>void client.openAdmin!(service.id).catch(e=>setError(e.message)):undefined}/></td></tr>)}</tbody></table></div>}
  </>}
  {!detail&&scope==='project'&&snapshot.project&&client.terraform&&<TerraformPanel key={snapshot.project} client={client} project={snapshot.project}/>}
  {detail&&<section className="rt-service-page">
   <nav aria-label="Breadcrumb" className="rt-service-breadcrumb"><button onClick={()=>setDetail(false)}>{scope==='project'?(snapshot.projects?.find(p=>p.path===snapshot.project)?.name??'Project'):'Global services'}</button><span aria-hidden="true">/</span><button onClick={()=>setDetail(false)}>Services</button><span aria-hidden="true">/</span><span aria-current="page">{current?.label??'Service'}</span></nav>
   {current?<><section className="rt-project-overview"><div><h2>{current.label} {current.runtime&&<span className="rt-runtime-badge">{current.runtime}</span>}</h2><span className={`rt-services-status state-${current.state}`}><i/>{current.state}</span></div><div className="rt-services-controls">{(['start','stop','restart'] as const).map(command=><button key={command} disabled={busy||(command==='start'&&['waiting','starting','running','stopping'].includes(current.state))||(command==='stop'&&!['waiting','starting','running','stopping'].includes(current.state))} onClick={()=>void action(command,current.id)}><ActionIcon action={command}/>{command[0].toUpperCase()+command.slice(1)}</button>)}</div></section>
   <div className="rt-service-metrics">{current.exitCode!==null&&<span>Exit code <strong>{current.exitCode}</strong></span>}<span>PID <strong>{current.pid??'—'}</strong></span><span>CPU <strong>{current.pid?`${current.cpu.toFixed(1)}%`:'—'}</strong></span><span>Memory <strong>{current.pid?`${current.memoryMb.toFixed(0)} MB`:'—'}</strong></span>{current.url&&<button className="rt-services-link" onClick={()=>void client.openUrl?.(current.id).catch(e=>setError(e.message))}>{current.url} ↗</button>}</div></>:<p>This service is no longer available.</p>}
  <div className="rt-services-detail"><div className="rt-services-detail-header"><div><strong>{current?.label??'Select a service'}</strong><span>Output · stdout + stderr</span></div><div className="rt-output-actions"><button disabled={!logs.length} onClick={()=>void copyOutput()}>{copied?'Copied!':'Copy output'}</button><label><input type="checkbox" checked={follow} onChange={e=>changeFollow(e.target.checked)}/> Follow output</label></div></div>
   {current?.error&&<p className="rt-services-error" role="alert">{current.error}</p>}
   {current?.ports?.length?<div className="rt-services-dependencies">Ports: {current.ports.join(', ')} · Host: localhost</div>:null}
   {current?.dependencies.length? <div className="rt-services-dependencies">Requires: {current.dependencies.join(', ')} {current.exitCode!==null?` · Exit code: ${current.exitCode}`:''}</div>:null}
   <pre ref={output} onWheel={e=>{if(e.deltaY<0)changeFollow(false);}} onKeyDown={e=>{if(['ArrowUp','PageUp','Home'].includes(e.key))changeFollow(false);}} onScroll={e=>{const el=e.currentTarget;if(el.scrollHeight-el.clientHeight-el.scrollTop>8)changeFollow(false);}} className="rt-services-output" tabIndex={0} aria-label="Service output">{logs.length?logs.map(row=><div key={row.sequence} className={row.stream==='stderr'?'stderr':''}><time>{new Date(Number(row.time)).toLocaleTimeString()}</time><span className="stream">{row.stream}</span>{row.text}</div>):<span className="rt-services-empty">No output yet. Start the service to see its logs.</span>}</pre>
  </div></section>}</>}<footer>Closing this window keeps the menu-bar manager and services running · JSON storage runs inside the API · CPU % and memory include child processes.</footer>
 </>}</main></div></section>;
}
export default ServiceManager;
