import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {readFile,writeFile,mkdir,chmod,rename,rm} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {homedir} from 'node:os';
import {createHash} from 'node:crypto';
import {run,packageRoot} from './index.mjs';
const exec=promisify(execFile);
export const requirements=[{id:'java',name:'Java · JDK 21',version:'temurin-21',command:'java',minimum:[21,0],description:'Required by a Java backend; includes javac.'},{id:'node',name:'Node.js + npm',version:'24',command:'node',minimum:[22,14],description:'Required by RT-App, React, Next.js and Electron.'},{id:'go',name:'Go',version:'1.26',command:'go',minimum:[1,22],description:'Optional unless a project declares a Go service.'},{id:'python',name:'Python',version:'3.14',command:'python3',minimum:[3,11],description:'Optional unless a project declares a Python service.'}];
export class Toolchains {
 constructor(home=join(homedir(),'.rt-app','service-manager')){this.home=join(home,'toolchains');this.bin=join(this.home,'mise');}
 async environment(){let paths=[];try{paths=JSON.parse(await readFile(join(this.home,'paths.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}return {...process.env,PATH:[...paths,process.env.PATH??''].join(':'),MISE_DATA_DIR:join(this.home,'data'),MISE_CACHE_DIR:join(this.home,'cache'),MISE_CONFIG_DIR:join(this.home,'config'),MISE_GLOBAL_CONFIG_FILE:join(this.home,'config.toml'),MISE_SYSTEM_CONFIG_FILE:join(this.home,'system.toml'),MISE_YES:'1',MISE_AUTO_INSTALL:'0'};}
 async status(required=['node']){const env=await this.environment();return Promise.all(requirements.map(async tool=>{let version='',ready=false;try{const r=await exec(tool.command,tool.id==='go'?['version']:['--version'],{env,timeout:5000});version=(r.stdout||r.stderr).trim();const match=version.match(/(\d+)\.(\d+)/);ready=!!match&&(Number(match[1])>tool.minimum[0]||Number(match[1])===tool.minimum[0]&&Number(match[2])>=tool.minimum[1]);if(tool.id==='java')await exec('javac',['--version'],{env,timeout:5000});if(tool.id==='node')await exec('npm',['--version'],{env,timeout:5000});}catch{ready=false;}return {...tool,required:required.includes(tool.id),ready,installedVersion:version};}));}
 async ensureMise(onLog){await mkdir(this.home,{recursive:true,mode:0o700});const manifest=JSON.parse(await readFile(join(packageRoot,'toolchain.json'),'utf8'));const asset=manifest.assets[`${process.platform}-${process.arch}`];if(!asset)throw new Error('Automatic toolchain installation supports macOS and Linux arm64/x64. Install the required tools manually on this platform.');
 const digest=bytes=>createHash('sha256').update(bytes).digest('hex');try{if(digest(await readFile(this.bin))===asset.sha256)return;}catch(e){if(e.code!=='ENOENT')throw e;}
 onLog('Downloading verified mise '+manifest.version+'…');const url=`https://github.com/jdx/mise/releases/download/v${manifest.version}/mise-v${manifest.version}-${asset.file}`;const response=await fetch(url,{signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error('mise download failed: '+response.status);const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>100*1024*1024||digest(bytes)!==asset.sha256)throw new Error('mise checksum mismatch');const temp=this.bin+'.tmp';await writeFile(temp,bytes,{mode:0o700});await chmod(temp,0o700);await rename(temp,this.bin);}
 async install(ids,onLog=()=>{}){if(!Array.isArray(ids)||!ids.length||ids.some(id=>!requirements.some(r=>r.id===id)))throw new Error('Invalid tool selection');await this.ensureMise(onLog);let paths=[];try{paths=JSON.parse(await readFile(join(this.home,'paths.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
 for(const id of [...new Set(ids)]){const tool=requirements.find(r=>r.id===id);onLog('Installing '+tool.name+' '+tool.version+'…');const env=await this.environment();await run(this.bin,['install',`${id}@${tool.version}`],{cwd:this.home,env,onLog});const {stdout}=await exec(this.bin,['which',tool.command==='python3'?'python':tool.command,'--tool',`${id}@${tool.version}`],{cwd:this.home,env,timeout:30000});paths=[dirname(stdout.trim()),...paths.filter(p=>p!==dirname(stdout.trim()))];await writeFile(join(this.home,'paths.json'),JSON.stringify(paths)+'\n',{mode:0o600});}
 return this.status();}
}
