import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,stat} from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {bootstrapAws,deploymentEnvironment,savedIdentity} from '../aws-bootstrap.mjs';
const env={RT_APP_BOOTSTRAP_ACCESS_KEY_ID:'admin-id',RT_APP_BOOTSTRAP_SECRET_ACCESS_KEY:'admin-secret',RT_APP_BOOTSTRAP_SESSION_TOKEN:'admin-token',AWS_REGION:'us-east-1'};
async function fixture(){const root=await mkdtemp(join(tmpdir(),'rt-bootstrap-test-'));await writeFile(join(root,'package.json'),JSON.stringify({name:'demo'}));return root;}
function mocks(fail){const calls=[];return {calls,stsFactory:()=>({send:async()=>({Account:'123456789012',Arn:'arn:aws:iam::123456789012:user/admin'}),destroy(){}}),iamFactory:options=>{assert.equal(options.credentials.sessionToken,'admin-token');return {destroy(){},send:async command=>{calls.push(command);if(command.constructor.name===fail){const e=new Error('SECRET MUST NOT LEAK');e.name='AccessDenied';throw e;}if(command.constructor.name==='CreateAccessKeyCommand')return {AccessKey:{AccessKeyId:'deploy-id',SecretAccessKey:'deploy-secret'}};return {};}}}};}
test('creates scoped IAM user once, persists only deployment credentials privately and strips bootstrap environment',async()=>{
 const root=await fixture();try{const mock=mocks();const value=await bootstrapAws({root,env,...mock});assert.equal(value.app,'rt-app-demo');assert.deepEqual(mock.calls.map(c=>c.constructor.name),['CreateUserCommand','PutUserPolicyCommand','CreateAccessKeyCommand']);const policy=JSON.parse(mock.calls[1].input.PolicyDocument);assert.ok(JSON.stringify(policy).includes('rt-app-demo-*'));assert.ok(policy.Statement.find(s=>s.Sid==='ApplicationFunctions').Resource.includes('arn:aws:lambda:*:123456789012:function:rt-app-demo'));assert.ok(policy.Statement.find(s=>s.Sid==='ApplicationSecrets').Resource.includes('arn:aws:secretsmanager:*:123456789012:secret:rt-app-demo/*'));assert.ok(!JSON.stringify(policy).includes('role/rt-app-*'));const raw=await readFile(join(root,'.rt-app/aws-identity.json'),'utf8');assert.ok(!raw.includes('admin-secret'));assert.ok(!raw.includes('admin-token'));assert.equal((await stat(join(root,'.rt-app/aws-identity.json'))).mode&0o777,0o600);assert.deepEqual(await savedIdentity(root),value);
 const again=await bootstrapAws({root,env:{},iamFactory:()=>assert.fail('must not recreate user'),stsFactory:()=>assert.fail('must not require admin credentials again')});assert.deepEqual(again,value);const next=deploymentEnvironment({...env,AWS_SESSION_TOKEN:'old',AWS_PROFILE:'old'},value);assert.equal(next.AWS_ACCESS_KEY_ID,'deploy-id');assert.equal(next.AWS_SECRET_ACCESS_KEY,'deploy-secret');assert.equal(next.AWS_SESSION_TOKEN,undefined);assert.equal(next.AWS_PROFILE,undefined);assert.equal(next.RT_APP_BOOTSTRAP_ACCESS_KEY_ID,undefined);assert.equal(next.RT_APP_NAME,value.app);await assert.rejects(bootstrapAws({root,env:{RT_APP_NAME:'rt-app-other'}}),/different app/);
 }finally{await rm(root,{recursive:true,force:true});}
});
test('existing user is never adopted or modified',async()=>{const root=await fixture();try{const mock=mocks('CreateUserCommand');await assert.rejects(bootstrapAws({root,env,...mock}),e=>!e.message.includes('SECRET')&&/No existing IAM user/.test(e.message));assert.equal(mock.calls.length,1);assert.equal(await savedIdentity(root),null);}finally{await rm(root,{recursive:true,force:true});}});
test('failed policy creation rolls back only the newly created user',async()=>{const root=await fixture();try{const mock=mocks('PutUserPolicyCommand');await assert.rejects(bootstrapAws({root,env,...mock}),/rolled back/);assert.deepEqual(mock.calls.map(c=>c.constructor.name),['CreateUserCommand','PutUserPolicyCommand','DeleteUserPolicyCommand','DeleteUserCommand']);assert.equal(await savedIdentity(root),null);}finally{await rm(root,{recursive:true,force:true});}});
test('missing credentials fail before any AWS client and release the lock',async()=>{const root=await fixture();try{await assert.rejects(bootstrapAws({root,env:{},stsFactory:()=>assert.fail('network'),iamFactory:()=>assert.fail('network')}),/Set RT_APP_BOOTSTRAP/);await assert.rejects(stat(join(root,'.rt-app/aws-bootstrap.lock')),e=>e.code==='ENOENT');}finally{await rm(root,{recursive:true,force:true});}});
