import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,access} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import {generate,normalize,registries} from '../bin/create-crud.mjs';
import {JsonStore} from '@gsalgadotoledo/rt-app-json';
import {LocalMailbox} from '@gsalgadotoledo/rt-app-auth';
import {createApplication} from '@gsalgadotoledo/rt-app-framework';
import {passwordVerifier} from '@gsalgadotoledo/rt-app-myadmin/backend';
const project=fileURLToPath(new URL('../../../',import.meta.url));
const spec={name:'products',title:'Products',fields:[{name:'name',type:'string'},{name:'price',type:'number'},{name:'active',type:'boolean'}],actions:['publish']};
async function fixture(t){
  const base=join(project,'.rt-app');await mkdir(base,{recursive:true});const root=await mkdtemp(join(base,'crud-test-'));
  t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,'packages'));
  await writeFile(join(root,'package.json'),JSON.stringify({type:'module',private:true,workspaces:['packages/*'],rtApp:{}}));
  await writeFile(join(root,'modules.json'),JSON.stringify({modules:['content','infra','users','auth','acl']}));
  for(const [file,content] of Object.entries(registries([])))await writeFile(join(root,file),content);
  return root;
}
test('generator validates names, previews without writes and refuses overwrite/custom registry edits',async t=>{
  const root=await fixture(t);
  for(const name of ['../escape','auth','x;exit','__proto__'])assert.throws(()=>normalize({...spec,name}));
  assert.throws(()=>normalize({...spec,fields:[{name:'version',type:'number'}]}));
  const before=await readFile(join(root,'modules.json'),'utf8');
  assert.equal((await generate(root,spec,{dryRun:true})).dryRun,true);
  assert.equal(await readFile(join(root,'modules.json'),'utf8'),before);
  await assert.rejects(access(join(root,'packages/products')));
  await generate(root,spec);await assert.rejects(generate(root,spec),/already/);
  const cli=spawnSync(process.execPath,[fileURLToPath(new URL('../bin/rta.mjs',import.meta.url)),'create','crud','orders','--fields','title:string,paid:boolean?','--json'],{cwd:root,encoding:'utf8'});
  assert.equal(cli.status,0,cli.stderr);assert.equal(JSON.parse(cli.stdout).created,'packages/orders');
  assert.deepEqual(JSON.parse(await readFile(join(root,'modules.json'),'utf8')).generatedCrud.map(e=>e.name),['products','orders']);
  await writeFile(join(root,'packages/admin.js'),'// user edits');
  await assert.rejects(generate(root,{...spec,name:'invoices'}),/custom edits/);
  const result=spawnSync(process.execPath,[fileURLToPath(new URL('../bin/rta.mjs',import.meta.url)),'create','crud','../invalid','--json'],{cwd:root,encoding:'utf8'});
  assert.equal(result.status,1);
});
test('generated CRUD integrates ACL, admin, migrations, search, conditional writes and JSON persistence',async t=>{
  const root=await fixture(t);await generate(root,spec);
  const {featureFactories}=await import(pathToFileURL(join(root,'packages/index.js')));
  const file=join(root,'db.json'),store=new JsonStore(file);
  const app=createApplication({store,mailer:new LocalMailbox(),secret:'generator-secret-'.repeat(4),adminPasswordVerifier:await passwordVerifier('Generator-test-password!'),featureFactories});
  await app.migrate();
  const call=(method,path,body={},token='',query={})=>app.handle({method,path,body,query,headers:token?{authorization:'Bearer '+token}:{},ip:'test'});
  const rootSession=(await call('POST','/admin/identity/auth/login',{password:'Generator-test-password!'})).body;
  const input={name:'Keyboard',price:20,active:true};
  assert.equal((await call('GET','/products')).status,401);
  const user=await app.users.create({email:'crud@example.test',name:'Reader',password:'Generator-test-password!'},'user');
  let session=(await call('POST','/auth/login',{email:user.data.email,password:'Generator-test-password!'})).body;
  assert.equal((await call('GET','/products',{},session.token)).status,403);
  const owner=await app.users.create({email:'owner-crud@example.test',name:'Owner',password:'Generator-test-password!'},'owner');
  const ownerSession=(await call('POST','/auth/login',{email:owner.data.email,password:'Generator-test-password!'})).body;
  assert.equal((await call('GET','/products',{},ownerSession.token)).status,403);
  const result=await call('POST','/admin/app/products',input,rootSession.token);assert.equal(result.status,200);const item=result.body;
  assert.equal((await call('PATCH','/admin/app/products/'+item.id,{price:30,version:999},rootSession.token)).status,409);
  assert.equal((await call('POST','/admin/app/products/'+item.id+'/actions/publish',{version:1},rootSession.token)).status,501);
  assert.equal((await call('GET','/admin/modules',{},rootSession.token)).body.some(m=>m.id==='products'),true);
  assert.equal((await call('GET','/admin/app/products',{},rootSession.token,{name__contains:'key',price__gte:'10',active:'true'})).body.items.length,1);
  assert.equal((await call('GET','/admin/app/products',{},rootSession.token,{price__gte:'100'})).body.items.length,0);
  assert.equal((await call('GET','/admin/app/products',{},rootSession.token,{price__gte:'NaN'})).status,400);
  assert.equal((await call('PUT','/admin/app/acl/users/'+user.data.id,{role:'user',grants:['products.list','products.read']},rootSession.token)).status,200);
  session=(await call('POST','/auth/login',{email:user.data.email,password:'Generator-test-password!'})).body;
  assert.equal((await call('GET','/products',{},session.token)).status,200);
  assert.equal((await call('POST','/products',input,session.token)).status,403);
  const entry = await access(join(project, 'apps/lambda-ts/dist/index.js')).then(() => 'apps/lambda-ts/dist/index.js', () => 'templates/hello-world/apps/lambda-ts/dist/index.js');
  const {createLambdaHandler}=await import(pathToFileURL(join(project, entry)).href);
  const lambda=createLambdaHandler(async()=>app);
  const response=await lambda({rawPath:'/products',headers:{authorization:'Bearer '+session.token},requestContext:{http:{method:'GET',sourceIp:'test'}}});
  assert.equal(response.statusCode,200);assert.equal(JSON.parse(response.body).items[0].id,item.id);
  assert.equal((await new JsonStore(file).get('CRUD#products',item.id)).data.name,'Keyboard');
  const check=spawnSync(process.execPath,[fileURLToPath(new URL('../../../node_modules/typescript/bin/tsc',import.meta.url)),'--noEmit','--strict','--skipLibCheck','--jsx','react-jsx','--module','ESNext','--moduleResolution','Bundler','--target','ES2022','--resolveJsonModule','--allowSyntheticDefaultImports',join(root,'packages/products/ui/index.tsx')],{cwd:root,encoding:'utf8'});
  assert.equal(check.status,0,check.stdout+check.stderr);
  const contract=spawnSync(process.execPath,['--test',join(root,'packages/products/tests/crud.test.mjs')],{cwd:root,encoding:'utf8'});assert.equal(contract.status,0,contract.stdout+contract.stderr);
});
test('generated search traverses empty pages and preserves continuation bounds',async t=>{
  const root=await fixture(t);await generate(root,spec);
  const {search}=await import(pathToFileURL(join(root,'packages/products/src/search.js')));
  let calls=0;const store={list:async()=>({items:[{data:{name:++calls===3?'needle':'other'}}],cursor:String(calls)})};
  const page=await search(store,'pk',{q:'needle'},spec.fields,r=>r.data);assert.equal(calls,3);assert.equal(page.items[0].name,'needle');assert.equal(page.cursor,'3');
  calls=0;const empty=await search(store,'pk',{q:'missing'},spec.fields,r=>r.data);assert.equal(calls,10);assert.equal(empty.cursor,'10');
});
