import React,{useEffect,useState} from 'react';
import type {Api} from '@gsalgadotoledo/rt-app-admin-ui';
export default function ObserverPanel({api}:{api:Api}) {
 const [day,setDay]=useState(new Date().toISOString().slice(0,10)),[report,setReport]=useState<any>(),[error,setError]=useState(''),[level,setLevel]=useState('all'),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{let current=true;setBusy(true);setError('');setReport(undefined);api('/observer/report?day='+day).then(data=>{if(current)setReport(data);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[day,tick]);
 const max=Math.max(1,...(report?.hours??[]).map((h:any)=>h.requests+h.views));
 return <section className="observer-panel"><div className="section-head"><div><p className="eyebrow">TELEMETRY / OBSERVER</p><h1>Application activity</h1></div><div className="observer-toolbar"><label>Day · UTC<input type="date" value={day} max={new Date().toISOString().slice(0,10)} onChange={e=>setDay(e.target.value)}/></label><button disabled={busy} onClick={()=>setTick(t=>t+1)}>{busy?'Loading…':'Refresh'}</button></div></div>
 {error&&<p role="alert">{error}</p>}
 {report&&<><div className="observer-cards">{[['API requests captured',report.counts.requests],['SPA page views',report.counts.spa],['SSR page views',report.counts.ssr],['Errors',report.counts.errors],['Average API latency',report.averageMs+' ms']].map(([title,value])=><article key={title} className="observer-card"><span>{title}</span><strong>{value}</strong><small>Selected day · UTC</small></article>)}</div>
 {(report.health.failed>0||report.health.dropped>0)&&<p className="hint">Some output deliveries failed or were suppressed on this instance. Recorded counts may be incomplete.</p>}
 {report.partial&&<p role="alert">Partial report: the read limit was reached. Totals and rankings only include the events loaded.</p>}
 <div className="observer-grid"><article className="observer-box"><h2>Activity / 24 hours</h2><div className="observer-chart" role="img" aria-label="Hourly requests and page views. Hover a bar for counts.">{report.hours.map((h:any)=><div key={h.hour} title={`${h.hour}:00 UTC · ${h.requests} requests · ${h.views} views`}><div className="observer-bar" style={{height:((h.requests+h.views)/max*130)+'px'}}/><small>{h.hour%4===0?h.hour:''}</small></div>)}</div><p className="hint">Requests + page views · no simulated data</p></article>
 <article className="observer-box"><h2>Most visited pages</h2><table><thead><tr><th>Site</th><th>Page</th><th>Views</th></tr></thead><tbody>{report.pages.map((p:any)=><tr key={p.source+p.path}><td>{p.source.toUpperCase()}</td><td>{p.path}</td><td>{p.views}</td></tr>)}</tbody></table>{!report.pages.length&&<p className="hint">Open the SPA or SSR to record page views.</p>}</article></div>
 <div className="observer-grid"><article className="observer-box"><h2>Output handlers</h2>{report.outputs.map((o:any)=><div className="observer-output" key={o.id}><strong>{o.id}</strong><span>{o.enabled?'Enabled':'Disabled'}</span><small>{o.levels.join(' · ')}</small></div>)}<p className="hint">Configured in code. Email / SMS / CloudWatch are opt-in.</p></article><article className="observer-box"><h2>Delivery health / this API instance</h2><div className="observer-cards"><div><strong>{report.health.failed}</strong><p>Failed deliveries</p></div><div><strong>{report.health.dropped}</strong><p>Rate / capacity drops</p></div></div><p className="hint">Seven-day retention. Visits are client-reported events, not unique visitors. External handlers can add delivery latency.</p></article></div>
 <div className="observer-grid">{[['API latency by route',report.requestMetrics??[]],['Measured operations',report.operationMetrics??[]]].map(([title,rows]:any)=><article className="observer-box" key={title}><h2>{title}</h2><table><thead><tr><th>Name</th><th>Count</th><th>Avg ms</th><th>Min / max ms</th><th>Errors</th></tr></thead><tbody>{rows.map((m:any)=><tr key={m.source+m.name}><td>{m.name}<small> · {m.source}</small></td><td>{m.count}</td><td>{m.averageMs}</td><td>{Math.round(m.minMs)} / {Math.round(m.maxMs)}</td><td>{m.errors}</td></tr>)}</tbody></table>{!rows.length&&<p className="hint">No measurements recorded.</p>}</article>)}</div>
 <article className="observer-box"><div className="section-head"><h2>Event stream / last 100 loaded</h2><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}>{['all','debug','info','warn','error'].map(l=><option key={l}>{l}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Level</th><th>Source</th><th>Event</th><th>Details</th></tr></thead><tbody>{report.events.filter((e:any)=>level==='all'||e.level===level).map((e:any)=><tr key={e.id}><td>{e.at.slice(11,19)}</td><td><span className={'log-level '+e.level}>{e.level}</span></td><td>{e.source}</td><td>{e.message}</td><td><code>{JSON.stringify(e.data)}</code></td></tr>)}</tbody></table></div></article></>}
 </section>;
}
